INSERT INTO public.ingredient (id, description, image_url, name, unit) VALUES (1, 'Salt is a mineral composed primarily of sodium chloride (NaCl), a chemical compound belonging to the larger class of salts; salt in its natural form as a crystalline mineral is known as rock salt or halite.', 'https://news.yale.edu/sites/default/files/styles/featured_media/public/adobestock_196225285.jpeg?itok=FyR9F85F&c=07307e7d6a991172b9f808eb83b18804', 'Salt', 0);
INSERT INTO public.ingredient (id, description, image_url, name, unit) VALUES (2, 'Sugar is the generic name for sweet-tasting, soluble carbohydrates, many of which are used in food. Simple sugars, also called monosaccharides, include glucose, fructose, and galactose.', 'https://images.immediate.co.uk/production/volatile/sites/4/2018/08/iStock_63854727_LARGE-a43c35e.jpg?quality=45&resize=960,413', 'Sugar', 0);
INSERT INTO public.ingredient (id, description, image_url, name, unit) VALUES (3, 'The chili pepper (also chile, chile pepper, chilli pepper, or chilli[4]), from Nahuatl chīlli  is the fruit of plants from the genus Capsicum which are members of the nightshade family.', 'https://cdn.shopify.com/s/files/1/1537/5553/products/12416_1024x1024.jpg?v=1486447009', 'Pepper', 0);
INSERT INTO public.ingredient (id, description, image_url, name, unit) VALUES (4, 'Milk is a nutrient-rich, white liquid food produced by the mammary glands of mammals. It is the primary source of nutrition for infant mammals (including humans who are breastfed) before they are able to digest other types of food. ', 'https://dairyfarmersofcanada.ca/sites/default/files/styles/full_width_large/public/getty-854296650.jpg?itok=oVdN6l2l', 'Milk', 1);
INSERT INTO public.ingredient (id, description, image_url, name, unit) VALUES (5, 'Honey is a sweet, viscous food substance made by bees and some related insects. Bees produce honey from the sugary secretions of plants (floral nectar) or from secretions of other insects (such as honeydew), by regurgitation, enzymatic activity, and water evaporation.', 'https://ichef.bbci.co.uk/news/660/cpsprodpb/49EA/production/_103122981_honey.jpg', 'Honey', 4);
INSERT INTO public.ingredient (id, description, image_url, name, unit) VALUES (6, 'Chocolate is a usually sweet, brown food preparation of roasted and ground cacao seeds that is made in the form of a liquid, paste, or in a block, or used as a flavoring ingredient in other foods.', 'https://static.independent.co.uk/s3fs-public/thumbnails/image/2017/07/07/14/melting-choc-istock.jpg?w968h681', 'Chocolate', 0);
INSERT INTO public.ingredient (id, description, image_url, name, unit) VALUES (7, 'A mushroom, or toadstool, is the fleshy, spore-bearing fruiting body of a fungus, typically produced above ground, on soil, or on its food source.', 'https://images-na.ssl-images-amazon.com/images/I/71LhWci7mFL._SX522_.jpg', 'Mushroom', 0);
INSERT INTO public.ingredient (id, description, image_url, name, unit) VALUES (8, 'Butter is a dairy product with high butterfat content which is solid when chilled and at room temperature in some regions, and liquid when warmed.', 'https://upload.wikimedia.org/wikipedia/commons/d/d3/%C5%A0v%C3%A9dsk%C3%BD_kol%C3%A1%C4%8D_naruby_904_%28cropped%29.JPG', 'Butter', 0);

