INSERT INTO public.recipe (id, description, directions, image, name, servings) VALUES (1, 'Description of French fries.', 'ut the potatoes lengthwise into 1/4-inch-thick slices, then cut each slice lengthwise into 1/4-inch-thick fries. Put the fries in a large bowl of cold water and refrigerate for at least 1 hour or up to 8 hours.', 'https://mediterran.cafeblog.hu/files/2019/02/A-legropog%C3%B3sabb-h%C3%A1zi-s%C3%BClt-krumpli-titka-glut%C3%A9nmentes2.jpg', 'French fries', 1);
INSERT INTO public.recipe (id, description, directions, image, name, servings) VALUES (2, 'Fried cheese is a dish prepared using cheese that is fried in oil.', 'Sprinkle cheese with optional salt, if desired. Dredge slices in flour, then in beaten egg, and finally in bread crumbs, making sure the cheese slices are completely covered. Pan fry quickly in hot oil or shortening until golden brown. Serve immediately.', 'https://kep.cdn.indexvas.hu/1/0/1877/18770/187708/18770865_216b5062d3bc18253f023449fe44f88b_wm.jpg', 'Fried cheese', 2);
INSERT INTO public.recipe (id, description, directions, image, name, servings) VALUES (3, 'A delicious pumpkin cookie that can be eaten single or filled with whoopie.', 'Preheat oven to 350 degrees F (175 degrees C). Lightly grease baking sheets. Combine the oil and brown sugar. Mix in the pumpkin and eggs, beating well. Add the flour, salt, baking powder, baking soda, 1 teaspoon vanilla, cinnamon, ginger and cloves. Mix well.', 'https://images.media-allrecipes.com/userphotos/720x405/744202.jpg', 'Pumpkin Pies', 2);
INSERT INTO public.recipe (id, description, directions, image, name, servings) VALUES (4, 'A perfectly seasoned and juicy turkey. ', 'Rub the turkey inside and out with the kosher salt. Place the bird in a large stock pot, and cover with cold water. Place in the refrigerator, and allow the turkey to soak in the salt and water mixture 12 hours, or overnight.t', 'https://images.media-allrecipes.com/userphotos/720x405/6573896.jpg', 'Perfect Turkey', 1);
INSERT INTO public.recipe (id, description, directions, image, name, servings) VALUES (5, 'Garnish with thinly sliced green onions, if desired.', 'Mix honey, tomato paste, apple cider vinegar, Sriracha sauce, and sesame oil together in a medium bowl. Step 2 Combine cold water, cornstarch, and 1/2 teaspoon salt in a bowl; mix well. Add to honey sauce mixture and mix well. Set aside until needed. Step 3 Sprinkle 1/4 teaspoon salt and 1/4 teaspoon garlic powder over chicken.', 'https://mediterran.cafeblog.hu/files/2019/02/A-legropog%C3%B3sabb-h%C3%A1zi-s%C3%BClt-krumpli-titka-glut%C3%A9nmentes2.jpg', 'Honey Chicken', 1);
INSERT INTO public.recipe (id, description, directions, image, name, servings) VALUES (6, 'This recipe features an icing made with cream cheese, cocoa, and cinnamon frosts this dark chocolate cake for an elegant dessert', 'Preheat oven to 350 degrees F (175 degrees C). Grease 3 - 9 inch round cake pans. In medium bowl, pour boiling water over cocoa, and whisk until smooth. Let mixture cool. Sift together flour, baking soda, baking powder and salt; set aside.In a large bowl, cream butter and sugar together until light and fluffy. Beat in eggs one at time, then stir in vanilla. Add the flour mixture alternately with the cocoa mixture. Spread batter evenly between the 3 prepared pans.Bake in preheated oven for 25 to 30 minutes. Allow to cool..', 'https://images.media-allrecipes.com/userphotos/720x405/844348.jpg', 'Chocolate Cake', 2);
INSERT INTO public.recipe (id, description, directions, image, name, servings) VALUES (7, 'This sauce is excellent over most grilled meats, including veal or beef medallions.', 'Melt butter in a saucepan over medium heat. Saute shallots briefly, then stir in all of the mushrooms. Saute until tender and translucent, about 3 minutes. Pour in red wine, and simmer for 3 minutes. Stir in demi glace, and simmer for 6 minutes, or until sauce has thickened.', 'https://images.media-allrecipes.com/userphotos/560x315/2428593.jpg', 'Mushroom Sauce', 2);
INSERT INTO public.recipe (id, description, directions, image, name, servings) VALUES (8, 'These are a version of a classic Austrian dessert. A nutty dough with preserves and a lattice top. A beautiful treat for the holidays', 'In a medium bowl, cream together the butter and sugar. Beat in the egg and lemon peel. In another bowl, stir together the flour, almonds, cinnamon and cloves. Gradually stir the dry ingredients into the creamed mixture. The dough will be stiff, so you may need to knead it by hand to get it to come together. Press half of the dough into the bottom of the prepared pan.', 'https://images.media-allrecipes.com/userphotos/720x405/4589657.jpg', 'Linzer Cookies', 1);

INSERT INTO public.recipe_ingredients (recipe_id, ingredients, ingredients_key) VALUES (1, 1, 1);
INSERT INTO public.recipe_ingredients (recipe_id, ingredients, ingredients_key) VALUES (1, 1, 3);
INSERT INTO public.recipe_ingredients (recipe_id, ingredients, ingredients_key) VALUES (2, 2, 1);
INSERT INTO public.recipe_ingredients (recipe_id, ingredients, ingredients_key) VALUES (2, 1, 3);
INSERT INTO public.recipe_ingredients (recipe_id, ingredients, ingredients_key) VALUES (2, 1, 4);
INSERT INTO public.recipe_ingredients (recipe_id, ingredients, ingredients_key) VALUES (3, 2, 1);
INSERT INTO public.recipe_ingredients (recipe_id, ingredients, ingredients_key) VALUES (3, 1, 2);
INSERT INTO public.recipe_ingredients (recipe_id, ingredients, ingredients_key) VALUES (3, 1, 3);
INSERT INTO public.recipe_ingredients (recipe_id, ingredients, ingredients_key) VALUES (3, 1, 4);
INSERT INTO public.recipe_ingredients (recipe_id, ingredients, ingredients_key) VALUES (4, 2, 1);
INSERT INTO public.recipe_ingredients (recipe_id, ingredients, ingredients_key) VALUES (4, 1, 2);
INSERT INTO public.recipe_ingredients (recipe_id, ingredients, ingredients_key) VALUES (4, 1, 3);
INSERT INTO public.recipe_ingredients (recipe_id, ingredients, ingredients_key) VALUES (4, 1, 4);
INSERT INTO public.recipe_ingredients (recipe_id, ingredients, ingredients_key) VALUES (5, 2, 1);
INSERT INTO public.recipe_ingredients (recipe_id, ingredients, ingredients_key) VALUES (5, 1, 4);
INSERT INTO public.recipe_ingredients (recipe_id, ingredients, ingredients_key) VALUES (5, 2, 5);
INSERT INTO public.recipe_ingredients (recipe_id, ingredients, ingredients_key) VALUES (6, 1, 1);
INSERT INTO public.recipe_ingredients (recipe_id, ingredients, ingredients_key) VALUES (6, 3, 2);
INSERT INTO public.recipe_ingredients (recipe_id, ingredients, ingredients_key) VALUES (6, 3, 3);
INSERT INTO public.recipe_ingredients (recipe_id, ingredients, ingredients_key) VALUES (6, 2, 6);
INSERT INTO public.recipe_ingredients (recipe_id, ingredients, ingredients_key) VALUES (7, 1, 1);
INSERT INTO public.recipe_ingredients (recipe_id, ingredients, ingredients_key) VALUES (7, 1, 2);
INSERT INTO public.recipe_ingredients (recipe_id, ingredients, ingredients_key) VALUES (7, 1, 4);
INSERT INTO public.recipe_ingredients (recipe_id, ingredients, ingredients_key) VALUES (7, 4, 7);
INSERT INTO public.recipe_ingredients (recipe_id, ingredients, ingredients_key) VALUES (7, 2, 8);
INSERT INTO public.recipe_ingredients (recipe_id, ingredients, ingredients_key) VALUES (8, 1, 1);
INSERT INTO public.recipe_ingredients (recipe_id, ingredients, ingredients_key) VALUES (8, 3, 2);
INSERT INTO public.recipe_ingredients (recipe_id, ingredients, ingredients_key) VALUES (8, 1, 4);
INSERT INTO public.recipe_ingredients (recipe_id, ingredients, ingredients_key) VALUES (8, 2, 8);
